# Generated by Django 4.2.7 on 2023-11-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="questionthree",
            table_comment="Table comment 2",
        ),
    ]
